# Copyright (c) 2024-2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[project]
name = "rapids-metadata"
version = "0.4.0"
authors = [
    { name = "RAPIDS Development Team", email = "pypi@rapids.ai" }
]
description = "metadata for structure of RAPIDS projects"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.9"
dependencies = [
    "packaging",
    "pydantic",
]

[project.scripts]
rapids-metadata-json = "rapids_metadata.json:main"

[project.urls]
Homepage = "https://github.com/rapidsai/rapids-metadata"
Documentation = "https://docs.rapids.ai/"
Source = "https://github.com/rapidsai/rapids-metadata"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=77.0.0",
    "wheel",
] # This list was generated by `rapids-dependency-file-generator`. To make changes, edit dependencies.yaml and run `rapids-dependency-file-generator`.

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-httpserver",
] # This list was generated by `rapids-dependency-file-generator`. To make changes, edit dependencies.yaml and run `rapids-dependency-file-generator`.

[tool.setuptools]
packages = { "find" = { where = ["src"] } }

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
